version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: styleguard-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./styleguard.db
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - OLLAMA_API_URL=http://192.168.1.73:11434/api/generate
      - MODEL_NAME=${MODEL_NAME}
    volumes:
      - ./api/styleguard.db:/app/styleguard.db
    ports:
      - "${API_PORT:-9080}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: styleguard-front
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-9081}:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: styleguard-network 