version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: styleguard-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///styleguard.db
      - SECRET_KEY=your_secret_key_here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./api/styleguard.db:/app/styleguard.db
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: styleguard-front
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: styleguard-network 