services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: styleguard-api
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///./styleguard.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-please-change-in-production}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      - OLLAMA_API_URL=http://192.168.1.73:11434/api/generate
      - MODEL_NAME=${MODEL_NAME:-gemma3:1b}
      - VITE_API_URL=${VITE_API_URL:-http://192.168.1.73:9080}
      - FRONTEND_URL=${FRONTEND_URL:-http://192.168.1.73:9081}
    volumes:
      - db-data:/app
    ports:
      - "${API_PORT:-9080}:8000"
    command: bash -c "python create_tables_async.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://192.168.1.73:9080}
        - FRONTEND_URL=${FRONTEND_URL:-http://192.168.1.73:9081}
    container_name: styleguard-front
    restart: unless-stopped
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-http://192.168.1.73:9081}
    # Optimisations pour Portainer
    shm_size: '1gb'
    mem_limit: '1gb'
    # Volumes pour le cache npm
    volumes:
      - npm-cache:/home/node/.npm
    ports:
      - "${FRONTEND_PORT:-9081}:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: styleguard-network

volumes:
  db-data:
  npm-cache: 